---
AWSTemplateFormatVersion: 2010-09-09
Description: PhpMyadmin template
Metadata:

  Authors:
    Description: Rahul Sharma 
Parameters:
  DatabaseClusterEndpointAddress:
    Description: The RDS cluster endpoint address.
    Type: String
  EC2KeyName:
    AllowedPattern: ^([a-zA-Z0-9 @.`~!#$%^&*()_+,\\-])*$
    ConstraintDescription: Must be letters (upper or lower), numbers, and special characters.
    Description: Name of an EC2 KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
  PHPAlbTargetGroupArn:
    Description: The public application load balancer target group arn.
    Type: String
  Subnet:
    Description: Select number of subnets.
    Type: List<AWS::EC2::Subnet::Id>
  WebAsgMax:
    AllowedPattern: ^((?!0$)[1-2]?[0-9]|30)$
    ConstraintDescription: Must be a number between 1 and 30.
    Default: 4
    Description: Specifies the maximum number of EC2 instances in the Web Autoscaling Group.
    Type: String
  WebAsgMin:
    AllowedPattern: ^([0-0]?[0-9]|10)$
    ConstraintDescription: Must be a number between 0 and 10.
    Default: 2
    Description: Specifies the minimum number of EC2 instances in the Web Autoscaling Group.
    Type: String
  WebInstanceType:
    AllowedValues:
    - t2.nano 
    - t2.micro 
    - t2.small 
    - t2.medium 
    - t2.large 
    - t2.xlarge 
    - t2.2xlarge 
    - m3.medium 
    - m3.large 
    - m3.xlarge 
    - m3.2xlarge 
    - m4.large 
    - m4.xlarge 
    - m4.2xlarge 
    - m4.4xlarge 
    - m4.10xlarge 
    - m4.16xlarge 
    - m5.large 
    - m5.xlarge 
    - m5.2xlarge 
    - m5.4xlarge 
    - m5.12xlarge 
    - m5.24xlarge 
    - c3.large 
    - c3.xlarge 
    - c3.2xlarge 
    - c3.4xlarge 
    - c3.8xlarge 
    - c4.large 
    - c4.xlarge 
    - c4.2xlarge 
    - c4.4xlarge 
    - c4.8xlarge 
    - c5.large 
    - c5.xlarge 
    - c5.2xlarge 
    - c5.4xlarge 
    - c5.9xlarge 
    - c5.18xlarge
    - r3.large 
    - r3.xlarge 
    - r3.2xlarge 
    - r3.4xlarge 
    - r3.8xlarge 
    - r4.large 
    - r4.xlarge 
    - r4.2xlarge 
    - r4.4xlarge 
    - r4.8xlarge 
    - r4.16xlarge 
    - x1.16xlarge 
    - x1.32xlarge 
    - x1e.xlarge 
    - x1e.2xlarge 
    - x1e.4xlarge 
    - x1e.8xlarge 
    - x1e.16xlarge 
    - x1e.32xlarge
    - d2.xlarge 
    - d2.2xlarge 
    - d2.4xlarge 
    - d2.8xlarge 
    - h1.2xlarge 
    - h1.4xlarge 
    - h1.8xlarge 
    - h1.16xlarge 
    - i2.xlarge 
    - i2.2xlarge 
    - i2.4xlarge 
    - i2.8xlarge 
    - i3.large 
    - i3.xlarge 
    - i3.2xlarge 
    - i3.4xlarge 
    - i3.8xlarge 
    - i3.16xlarge
    - f1.2xlarge 
    - f1.16xlarge 
    - g2.2xlarge 
    - g2.8xlarge 
    - g3.4xlarge 
    - g3.8xlarge 
    - g3.16xlarge 
    - p2.xlarge 
    - p2.8xlarge 
    - p2.16xlarge 
    - p3.2xlarge 
    - p3.8xlarge 
    - p3.16xlarge
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: t2.large
    Description: The Amazon EC2 instance type for your web instances.
    Type: String
  WebSecurityGroup:
    Description: Select the web security group.
    Type: AWS::EC2::SecurityGroup::Id
  NumberOfSubnets:
    AllowedValues:
    - 2
    - 3
    - 4
    - 5
    - 6
    Default: 3
    Description: Number of subnets. This must match your selections in the list of subnets below.
    Type: String   
Mappings:
  RegionMap:
    ap-northeast-1:
      AMI: ami-da9e2cbc
    ap-northeast-2:
      AMI: ami-1196317f
    ap-south-1:
      AMI: ami-d5c18eba
    ap-southeast-1:
      AMI: ami-c63d6aa5
    ap-southeast-2:
      AMI: ami-ff4ea59d
    ca-central-1:
      AMI: ami-d29e25b6
    eu-central-1:
      AMI: ami-bf2ba8d0
    eu-west-1:
      AMI: ami-1a962263
    eu-west-2:
      AMI: ami-e7d6c983
    sa-east-1:
      AMI: ami-286f2a44
    us-east-1:
      AMI: ami-0ec44bde764230bed
    us-east-2:
      AMI: ami-0fcc099ed56d16d42
    us-west-1:
      AMI: ami-a51f27c5
    us-west-2:
      AMI: ami-bf4193c7
Conditions:
  NumberOfSubnets1:
    !Equals [ 1, !Ref NumberOfSubnets ]
  NumberOfSubnets2:
    !Equals [ 2, !Ref NumberOfSubnets ]
  NumberOfSubnets3:
    !Equals [ 3, !Ref NumberOfSubnets ]
  NumberOfSubnets4:
    !Equals [ 4, !Ref NumberOfSubnets ]
  NumberOfSubnets5:
    !Equals [ 5, !Ref NumberOfSubnets ]
  NumberOfSubnets6:
    !Equals [ 6, !Ref NumberOfSubnets ]
  Subnet0: !Or
    - !Condition NumberOfSubnets1
    - !Condition NumberOfSubnets2
    - !Condition NumberOfSubnets3
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet1: !Or
    - !Condition NumberOfSubnets2
    - !Condition NumberOfSubnets3
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet2: !Or
    - !Condition NumberOfSubnets3
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet3: !Or
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet4: !Or
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet5: !Condition NumberOfSubnets6        

Resources:
  PhpInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref PhpInstanceRole
  PhpInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: logs
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Resource:
            - arn:aws:logs:*:*:*
      - PolicyName: cloudwatch
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - cloudwatch:PutMetricData
            - ec2:DescribeTags
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            - logs:DescribeLogGroups
            - logs:CreateLogStream
            - logs:CreateLogGroup
            Resource:
            - "*"      
  PhpAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      Cooldown: 60
      HealthCheckGracePeriod: 120
      HealthCheckType: ELB
      LaunchConfigurationName: !Ref PhpLaunchConfiguration  
      MaxSize: 0
      MinSize: 0
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'Php ASG / ', !Ref 'AWS::StackName' ] ]
          PropagateAtLaunch: true
      TargetGroupARNs:
        - !Ref PHPAlbTargetGroupArn
      #VPCZoneIdentifier: [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ] ]
      VPCZoneIdentifier: 
         !If
          [ NumberOfSubnets1,
          [ !Select [ 0, !Ref Subnet ] ],
          !If
            [ NumberOfSubnets2,
            [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ] ],
            !If
              [ NumberOfSubnets3,
              [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ] ],
              !If
                [ NumberOfSubnets4,
                [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ], !Select [ 3, !Ref Subnet ] ],
                !If
                  [ NumberOfSubnets5,
                  [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ], !Select [ 3, !Ref Subnet ], !Select [ 4, !Ref Subnet ] ],
                  [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ], !Select [ 3, !Ref Subnet ], !Select [ 4, !Ref Subnet ], !Select [ 5, !Ref Subnet ] ]
                  ]
                ]
              ]
            ]
          ]   
       
  AutoScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
        AdjustmentType: ChangeInCapacity
        AutoScalingGroupName: !Ref PhpAutoScalingGroup
        Cooldown: 60
        PolicyType: SimpleScaling
        ScalingAdjustment: 1
  PhpCustomRamAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      #- !Ref SNSTopic
      - !Ref AutoScalingPolicy
      AlarmDescription: custom ram usage alarm.
      AlarmName: PHPMyadminRam Alarm.
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref PhpAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: mem_used
      Namespace: CustomMetric
      Period: 45
      Statistic: Sum
      Threshold: 70
      TreatMissingData: missing
  PhpCustomCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      #- !Ref SNSTopic
      - !Ref AutoScalingPolicy
      AlarmDescription: custom cpu usage alarm.
      AlarmName: PhpmyadminCPU Alarm.
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref PhpAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: cpu_usage_user
      Namespace: CustomMetric
      Period: 45
      Statistic: Sum
      Threshold: 70
      TreatMissingData: missing          
  PHPMyAdminDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: FARO-PhpAutoScalingGroup
      DashboardBody: {"Fn::Join":[ "",['{"widgets":[{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[[ "CustomMetric", "disk_used", "AutoScalingGroupName","',!Ref 'PhpAutoScalingGroup','" ]],"period":60,"region":"',!Ref 'AWS::Region','","title":"Disk Usage"}},{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[[ "CustomMetric", "disk_free", "AutoScalingGroupName","',!Ref 'PhpAutoScalingGroup','" ]],"period":60,"region":"',!Ref 'AWS::Region','","title":"Disk Free"}},{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[[ "CustomMetric", "disk_total", "AutoScalingGroupName","',!Ref 'PhpAutoScalingGroup','" ]],"period":60,"region":"',!Ref 'AWS::Region','","title":"Total Disk Space"}},{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[[ "CustomMetric", "disk_used_percent", "AutoScalingGroupName","',!Ref 'PhpAutoScalingGroup','" ]],"period":60,"region":"',!Ref 'AWS::Region','","title":"Disk Usage in Percentage"}},{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[[ "CustomMetric", "mem_used", "AutoScalingGroupName","',!Ref 'PhpAutoScalingGroup','" ]],"period":60,"region":"',!Ref 'AWS::Region','","title":"Memory Used"}},{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[[ "CustomMetric", "mem_used_percentage", "AutoScalingGroupName","',!Ref 'PhpAutoScalingGroup','" ]],"period":60,"region":"',!Ref 'AWS::Region','","title":"Memory Used in Percentage"}},{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[[ "CustomMetric", "mem_available", "AutoScalingGroupName","',!Ref 'PhpAutoScalingGroup','" ]],"period":60,"region":"',!Ref 'AWS::Region','","title":"Memory Available"}},{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[[ "CustomMetric", "mem_total", "AutoScalingGroupName","',!Ref 'PhpAutoScalingGroup','" ]],"period":60,"region":"',!Ref 'AWS::Region','","title":"Total Memory"}},{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[[ "CustomMetric", "mem_free", "AutoScalingGroupName","',!Ref 'PhpAutoScalingGroup','" ]],"period":60,"region":"',!Ref 'AWS::Region','","title":"Memory Free"}}]}']]}
  PhpLaunchConfiguration: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      IamInstanceProfile: !Ref PhpInstanceProfile
      ImageId: !FindInMap [ RegionMap, !Ref 'AWS::Region', AMI ]
      InstanceMonitoring: true
      InstanceType: !Ref WebInstanceType
      KeyName: !Ref EC2KeyName
      SecurityGroups:
      - !Ref WebSecurityGroup
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -xe
            sed -i "s/DBhost/${DatabaseClusterEndpointAddress}/" /etc/phpmyadmin/config.inc.php
            service apache2 restart
            
            
            
            
